import { brand } from "@/lib/brand";

const N = brand.name;

export const authCopy = {
  auth: {
    signInTitle: "Welcome back",
    signInSub: "Sign in to see what's on.",
    signUpTitle: "Create your account",
    signUpSub: "Takes a minute. You must be 18 or older.",
    name: "Your name",
    namePlaceholder: "First name is fine",
    username: "Username",
    usernamePlaceholder: "e.g. chanka",
    usernameHint: "3–20 characters: letters, numbers, underscores.",
    email: "Email",
    password: "Password",
    passwordHint: "At least 8 characters.",
    birthDate: "Date of birth",
    birthDateHint: "We show your age, never your birthday. Hosts can set an age range for their gigs.",
    gender: "Gender",
    genderHint: "Some gigs are women-only or men-only. This can't be changed later without contacting us.",
    genders: { woman: "Woman", man: "Man", nonbinary: "Non-binary" } as Record<string, string>,
    terms: "I'm 18 or older and I agree to the",
    termsLink: "Terms",
    and: "and",
    privacyLink: "Privacy Policy",
    signInCta: "Sign in",
    signUpCta: "Create account",
    working: "One sec…",
    toggleToSignUp: "New here? Create an account",
    toggleToSignIn: "Already have an account? Sign in",
    forgot: "Forgot password?",
    resetTitle: "Reset your password",
    resetSub: "We'll email you a link to set a new one.",
    resetCta: "Send reset link",
    resetSent: "If there's an account for that email, a reset link is on its way.",
    newPasswordTitle: "Choose a new password",
    newPasswordCta: "Save password",
    newPasswordDone: "Password updated.",
    backToSignIn: "Back to sign in",
    confirmEmail: "Almost there. We've sent you an email. Confirm your address, then sign in.",
    errors: {
      username_taken: "That username's taken. Try another.",
      username_format: "Usernames are 3–20 characters: letters, numbers, underscores.",
      bad_credentials: "That email or password isn't right.",
      email_in_use: "There's already an account with that email. Sign in instead.",
      email_not_confirmed: "Confirm your email first. Check your inbox for the link.",
      weak_password: "Use at least 8 characters.",
      name_required: "Add your name.",
      email_invalid: "That email doesn't look right.",
      birth_required: "Add your date of birth.",
      underage: `You need to be 18 or older to use ${N}.`,
      gender_required: "Pick a gender.",
      terms_required: "You need to accept the Terms and Privacy Policy.",
      rate_limited: "Too many attempts. Wait a minute and try again.",
      generic: "That didn't work. Try again in a moment.",
    } as Record<string, string>,
  },
  onboarding: {
    title: "One more step",
    sub: "Hosts can open gigs to an age range or to women/men only, so we need these two things before you can join.",
    cta: "Continue",
  },
  profile: {
    edit: "Edit profile",
    save: "Save changes",
    saved: "Saved",
    bio: "About you",
    bioPlaceholder: "What are you into? What are you looking for?",
    age: (n: number) => `${n}`,
    hostedCount: "Hosted",
    joinedCount: "Joined",
    reliability: "Reliability",
    notVerified: "Not verified",
    settings: "Account",
    installApp: "Install the app",
    deleteAccount: "Delete account",
    deleteConfirm: "This permanently deletes your account, profile, photos and gig history. Reports and moderation records are kept without your name. This can't be undone.",
    deleteType: "Type DELETE to confirm",
    deleteDo: "Delete my account",
    lockedField: "Contact us to change this.",
  },
  photo: {
    title: "Profile photo",
    hint: "A clear photo of your face, just you. It's checked by our team before anyone sees it, and only people in your gigs see it.",
    choose: "Upload a photo",
    change: "Change photo",
    checking: "Checking for a face…",
    uploading: "Uploading…",
    noFace: "We couldn't find a face in that photo. Use a clear, well-lit photo of just you.",
    manyFaces: "We found more than one face. Use a photo of just you.",
    pending: "Under review. It'll appear once approved.",
    approved: "Approved",
    rejected: "Your last photo wasn't approved",
    rejectReasons: {
      no_face: "We couldn't see a face.",
      not_you: "It didn't look like a real photo of you.",
      group_photo: "More than one person was in it.",
      inappropriate: "It broke our photo rules.",
      low_quality: "It was too blurry or dark.",
    } as Record<string, string>,
    tooBig: "That image is too large. Try a different one.",
    badType: "Use a JPG, PNG or WebP image.",
  },
  friends: {
    title: "Friends",
    requestSent: "Sent. If they add you back, you'll see the gigs they host.",
    requestReceived: (name: string, activity: string, date: string) =>
      `${name} wants to add you after ${activity} on ${date}.`,
    listEmpty: "No friends yet. Go to a gig, have a good time, add people afterwards.",
    yourFriends: "Your friends",
    incoming: "Wants to add you",
    outgoing: "Requests you sent",
    outgoingHint: "Waiting to hear back. You'll know if they add you, and only then.",
    add: "Add friend",
    added: "Request sent",
    accept: "Add back",
    unfriend: "Remove",
    invite: "Invite",
    inviteSent: "Invited",
    summaryTitle: "You did this together",
    summaryHint: "Had a good time with someone? Add them. You can only add people you actually met.",
    whyNoDms: {
      heading: "Why no private messages?",
      body: "Every conversation here happens with at least three people in it, on purpose. Private threads are how a friends app quietly turns into a dating app, and how people end up in one-on-one chats they didn't sign up for.",
      body2: "Adding a friend means their gigs show up for you and you can nudge them into yours. Want to talk? Post a plan.",
    },
  },
} as const;
