export const chatCopy = {
  chat: {
    heading: "Group chat",
    lockedTitle: "Chat unlocks when the gig is on",
    beforeConfirm: (n: number) =>
      `Chat and everyone's photos unlock once every spot is filled: ${n === 1 ? "1 more person" : `${n} more people`} to go. If it doesn't fill, they unlock 2 hours before the start.`,
    opens: "You're on. Sort out the details here.",
    readOnly: "This gig's finished. Chat is read-only and will be deleted after 30 days.",
    placeholder: "Message the crew",
    send: "Send",
    you: "You",
    someone: "Someone",
    system: {
      confirmed: "Every spot is filled. Chat and photos are unlocked.",
      locked: "Crew's locked in. Chat and photos are unlocked. See you there.",
      left: "Someone left the gig.",
      removed: "The host removed someone from the gig.",
      vote_removed: "The crew voted someone out of the gig.",
      cancelled: "The host cancelled this gig.",
      guest_joined: "Someone the host knows joined with a private invite link.",
    } as Record<string, string>,
  },
  vote: {
    action: "Vote to remove",
    title: (name: string) => `Vote to remove ${name}?`,
    body: "Use this for bad behaviour in chat or at the gig: harassment, pushiness, spam, sharing others' details. Votes are anonymous to the crew. If a majority of the other members agree, they're removed and our team reviews it.",
    reason: "What happened?",
    reasonPlaceholder: "A few words about the behaviour",
    submit: "Cast my vote",
    retract: "Withdraw my vote",
    tally: (v: number, n: number) => `${v} of ${n} votes to remove`,
    youVoted: "You voted",
    removed: "They've been removed. Thanks for keeping the group safe.",
    recorded: "Vote recorded. Nothing happens unless enough of the crew agree.",
    retracted: "Vote withdrawn.",
    hostNote: "Hosts can't be voted out. If the host is the problem, leave and report them.",
  },
  trust: {
    report: {
      title: "Report",
      intro: "Goes to our team only. It's never shown to the person or the rest of the crew.",
      category: "What happened?",
      details: "Tell us a bit more",
      detailsPlaceholder: "What happened, and when.",
      submit: "Send report",
      sent: "Thanks. Someone on our team will look into it.",
      categories: {
        harassment: "Harassment or bullying",
        sexual_advance: "Unwanted romantic or sexual advance",
        pressured_private_meeting: "Pushed to meet one-on-one",
        sharing_contact: "Pushed to share contact details",
        venue_changed_to_private: "Tried to move it somewhere private",
        no_show: "Didn't show up",
        impersonation: "Not who their photo says",
        underage: "Seems under 18",
        spam_or_promo: "Selling, spam or scam links",
        threat_or_violence: "Threat or violence",
        other: "Something else",
      } as Record<string, string>,
    },
    block: {
      action: "Block",
      confirmTitle: "Block this person?",
      confirmBody: "You won't see each other's gigs again and can't end up in the same gig. They won't be told.",
      confirm: "Block",
      done: "Blocked.",
    },
    remove: {
      action: "Remove (host)",
      title: "Remove from your gig",
      intro: "Removals are logged and reviewed. Use this for a real problem, not because you'd prefer someone else.",
      category: "Why?",
      reasonPlaceholder: "Add a short reason (at least ten characters).",
      submit: "Remove",
      categories: {
        abusive_in_chat: "Abusive in chat",
        pushing_for_one_on_one: "Pushing to meet one-on-one",
        sharing_contact: "Pushing for contact details",
        misrepresented_themselves: "Not who they said they were",
        safety_concern: "Safety concern",
        other: "Something else",
      } as Record<string, string>,
    },
    cancel: "Cancel",
    close: "Close",
  },
} as const;
