export const discoverCopy = {
  privacy: {
    title: "Who can find it",
    public: "Public",
    publicHint: "Shows up in Discover for everyone inside your audience.",
    private: "Private",
    privateHint: "Never shown in any feed. Only people with one of your personal links can join.",
    badge: "Private",
    unused: (n: number) => (n === 1 ? "1 invite not used yet" : `${n} invites not used yet`),
    allHeld: (n: number) => (n === 1 ? "1 personal link to share" : `${n} personal links to share`),
    lobbyNote: "This gig is private. It doesn't appear in anyone's feed, and the only way in is one of the host's personal links.",
    linksTitle: "Your private links",
    linksSub: "One link per person. Each works once, then it's used up. Send each person their own link; don't post them in groups or anywhere public.",
    reset: "Reset link",
    resetConfirm: "Reset this link? The old one stops working and you get a fresh one for the same seat.",
    landingNote: "This is a private gig. It isn't listed anywhere, so this personal link is the only way in.",
  },
  nearby: {
    allAreas: "All areas",
    closest: "Closest first",
    soonest: "Soonest first",
    locating: "Finding you…",
    denied: "Location is off for this site. Turn it on in your browser to sort by distance.",
    unavailable: "Couldn't get your location. Try again or pick an area.",
    areaLabel: "Area",
    sortLabel: "Sort",
    privacyHint: "Your location is rounded to about 1 km, only used to sort this list, and never saved to your account.",
    away: (km: number) => (km < 1 ? "Under 1 km away" : `${km < 10 ? km.toFixed(1) : Math.round(km)} km away`),
    emptyArea: (area: string) => `Nothing on in ${area} right now. Try another area or post one.`,
  },
} as const;
