export const errorsCopy = {
  errors: {
    gig_full: "That gig just filled up. There are others on.",
    gig_locked: "Joining closed 2 hours before the start.",
    gig_not_open: "This gig isn't taking people right now.",
    gig_not_found: "That gig's gone.",
    gig_not_active: "This gig has finished.",
    already_in_crew: "You're already in this one.",
    removed_from_gig: "You can't rejoin a gig you were removed from.",
    not_eligible: "This gig is set for a different age range or audience.",
    account_restricted: "You can't join gigs right now. Check your email for details.",
    not_authenticated: "Sign in first.",
    profile_incomplete: "Add your date of birth and gender first.",
    profile_missing: "Your profile isn't set up yet. Reload and try again.",
    capacity_too_low: "A gig needs at least three people.",
    capacity_too_high: "Keep it to 16 people or fewer.",
    too_many_guests: "Leave at least one spot open for the public.",
    bad_age_range: "Check the age range.",
    host_outside_age_range: "Your own age needs to be inside the age range.",
    host_gender_mismatch: "You can only host a women-only or men-only gig if you're in that group.",
    too_many_open_gigs: "You've got 5 upcoming gigs already. Let some happen first.",
    starts_too_soon: "Give people time to see it — start at least 3 hours from now.",
    starts_too_far: "Keep it within the next 60 days.",
    posting_restricted: "You can't host gigs right now. Check your email.",
    reason_too_short: "Add a bit more detail.",
    already_removed_from_gig: "You've already removed someone from this gig.",
    removal_limit_reached: "You've hit the removal limit for this month. Email us if there's a real problem.",
    cannot_report_self: "You can't report yourself.",
    too_many_reports: "You've sent a lot of reports today. Email us if it's urgent.",
    details_required: "Add a short description.",
    chat_not_open: "Voting opens once the gig is on.",
    cannot_vote_self: "You can't vote on yourself.",
    cannot_kick_host: "Hosts can't be voted out — leave and report them instead.",
    not_enough_voters: "There need to be at least two other people in the gig to vote. Leave and report instead.",
    target_not_in_crew: "They're not in this gig any more.",
    not_in_crew: "You're not in this gig.",
    invite_not_found: "This invite link doesn't work any more.",
    invite_used: "This invite has already been used. Each link only works once.",
    nothing_reserved: "There are no held seats left.",
    checkin_closed: "Check-in is open from 30 minutes before the start.",
    residential: "That looks like a home address. Gigs must be at a public place — a café, court, park or venue.",
    no_shared_attendance: "You can only add people you've actually been to a gig with.",
    recently_asked: "You've already asked. Give it some time.",
    too_many_pending: "You've got a lot of requests out. Wait for some answers first.",
    not_available: "That didn't work. Try again later.",
    verification_cooldown: "Your last attempt didn't pass, so there's a short wait before trying again.",
    verification_rate_limited: "You've had a few goes today. Try again tomorrow.",
    challenge_expired: "That took too long and the code expired. Let's start again.",
    already_submitted: "This one's already in for review.",
    already_verified: "You're already verified.",
    bad_media_path: "Something went wrong saving that recording. Try again.",
    request_not_found: "That session expired. Start again.",
    underage: "You need to be 18 or older.",
    already_redeemed: "Already redeemed.",
    not_host: "Only the host can do that.",
    generic: "That didn't work. Try again in a moment.",
  } as Record<string, string>,
} as const;
