export const gigsCopy = {
  feed: {
    title: "Discover",
    greeting: (name: string) => `Hey ${name}`,
    sub: "Gigs near you that are open to you.",
    all: "All",
    empty: "Nothing on yet. Someone has to go first — might as well be you.",
    emptyFiltered: "No gigs in this category right now. Post one and see who bites.",
    emptyCta: "Post a gig",
    fromFriends: "Hosted by your friends",
    audienceNote: "You only see gigs whose age range and audience include you.",
    seeGig: "View gig",
    spotsLeft: (n: number) => (n === 1 ? "1 spot left" : `${n} spots left`),
    full: "Full",
    locked: "Locked",
  },
  venue: {
    openInMaps: "Open in Google Maps",
    searchPlaceholder: "Search a café, court, park or venue",
    searchHint: "Public places only — home addresses aren't allowed.",
    searching: "Searching…",
    change: "Change venue",
    searchLabel: "Search venues",
  },
  slots: {
    needMore: (n: number) => (n === 1 ? "1 more needed to go ahead" : `${n} more needed to go ahead`),
    on: "Chat open",
    hostTitle: "Host",
  },
  myGigs: {
    title: "My gigs",
    upcoming: "Upcoming",
    past: "Past",
    hosting: "Hosting",
    joined: "Joined",
    emptyUpcoming: "You're not in anything yet. Find a gig or post your own.",
    emptyPast: "Your finished gigs will show up here.",
    findGig: "Find a gig",
  },
  audience: {
    everyone: "Everyone",
    women: "Women only",
    men: "Men only",
    ages: (min: number, max: number) => (min === 18 && max === 99 ? "18+" : max === 99 ? `${min}+` : `${min}–${max}`),
  },
  guests: {
    badge: (n: number) => `Host +${n}`,
    feedNote: (n: number) => `The host is bringing ${n} ${n === 1 ? "friend" : "friends"} — join at your own risk.`,
    lobbyNote: (n: number) =>
      `The host is bringing ${n} ${n === 1 ? "person they know" : "people they know"}. They may already know each other, so the group dynamic might not be all strangers. Join at your own risk.`,
    joinedSoFar: (n: number) => `${n} of them ${n === 1 ? "has" : "have"} joined using the host's private link.`,
    ack: "I understand the host is bringing people they know, and I'm joining at my own risk.",
    reservedLeft: (n: number) => `${n} ${n === 1 ? "seat" : "seats"} held for the host's friends`,
  },
  gig: {
    confirmed: "It's on. Chat's open.",
    take: "Join this gig",
    joining: "Joining…",
    youreIn: "You're in",
    leave: "Leave gig",
    hostedBy: "Hosted by",
    mustAgree: "Tick the box to confirm you get what Tremigos is for.",
    needTime: "Pick a date and time first.",
    needVenue: "Pick a venue from the search.",
    perkTitle: "Perk for your crew",
    redeem: "Mark as redeemed",
    redeemed: "Redeemed",
    showCode: "Show this code at the venue",
    cancel: "Cancel gig",
    cancelConfirm: "Cancel this gig? Everyone in it will be told. Cancelling a gig that's already on counts against your reliability.",
    cancelDo: "Yes, cancel it",
    keep: "Keep it",
    cancelled: "This gig was cancelled.",
    status: {
      open: "Open",
      locked: "Locked in",
      completed: "Done",
      cancelled: "Cancelled",
      expired: "Expired",
    } as Record<string, string>,
  },
  newGig: {
    heading: "Post a gig",
    sub: "Pick the activity, set the time and place, and decide who it's for.",
    step1: "Activity",
    step2: "Details",
    step3: "Who's it for",
    step4: "Group size",
    pickActivity: "What are you up for?",
    title: "Give it a title",
    titlePlaceholder: "Friday night futsal, all levels",
    when: "Date & time",
    whenHint: "At least 3 hours from now. Joining closes 2 hours before it starts.",
    length: "Length",
    where: "Where",
    costNote: "Cost",
    optional: "optional",
    costPlaceholder: "Court fee ~LKR 1,000 each",
    notes: "Notes",
    notesPlaceholder: "Bring water. Beginners welcome.",
    audience: "Who can see and join",
    audienceHint: "People outside this won't see the gig at all.",
    ageRange: "Age range",
    ageRangeHint: "Your own age has to be inside the range.",
    gender: "Open to",
    howMany: "Total group size",
    howManyHint: "Including you. Minimum 3.",
    guests: "Bringing people you know?",
    guestsHint:
      "Hold seats for friends who are coming with you. Everyone will see that you're bringing people, and you'll get a link your friends can use to join the chat.",
    guestsNone: "Just me",
    openSpots: (n: number) => (n === 1 ? "1 spot open to the public" : `${n} spots open to the public`),
    submit: "Post the gig",
    submitting: "Posting…",
    minutes: "min",
  },
  invite: {
    title: "Links for your guests",
    sub: "One private link per person you're bringing. Each link works once — when your friend joins with it, it's used up. Send each person their own link; don't post them in groups.",
    guest: (n: number) => `Guest ${n}`,
    unused: "Not used yet",
    joined: (name: string) => `Joined · ${name}`,
    revoked: "Cancelled",
    copy: "Copy",
    copied: "Copied",
    share: "Share",
    shareText: (title: string) => `You're invited to join me on Tremigos: ${title}. This link is just for you and works once.`,
    revoke: "Cancel link",
    revokeConfirm: "Cancel this link? It stops working and the seat opens to the public.",
    landingTitle: (host: string) => `${host} invited you`,
    landingSub: "This is a personal, one-time invite to join this gig and its group chat.",
    joinCta: "Join with this invite",
    signInToJoin: "Sign up or sign in to join",
    notFound: "This invite link doesn't work any more. Ask the host for a new one.",
    used: "This invite has already been used. Each link only works once — ask the host for your own.",
    friendsFeature: "Nudge Tremigos friends",
    friendsHint: "Sends them a heads-up about this gig. It doesn't hold a seat — they join like anyone else.",
  },
  lobby: {
    whenWhere: "When & where",
    crew: "The crew",
    about: "About this gig",
    joinHint: "Spots are first-come. The group chat and photos unlock once every spot is filled.",
    leaving: "Leaving?",
    somethingCameUp: "Something came up",
    didntFeelComfortable: "I didn't feel comfortable",
    leaveHint: "The second option never counts against you, at any time, and quietly flags it to our team.",
    neverMind: "Never mind",
    youAreHost: "You're hosting",
    invitedByHost: "Host's guest",
    you: "You",
    previewBlind: "Join to see who's in. Photos and the group chat unlock once every spot is filled.",
    unlockHint: "Photos and the group chat unlock when every spot is filled (or 2 hours before the start).",
    checkinTitle: "Who showed up?",
    checkinHint: "Tap everyone you actually met. It keeps reliability honest — and unlocks adding friends afterwards.",
    checkedIn: "Confirmed",
    confirm: "Confirm",
    notOpenToYou: "This gig isn't open to you.",
  },
} as const;
