export const verificationCopy = {
  verification: {
    title: "Verify you're you",
    meaning:
      "Verified means a real person recorded themselves live, and a person on our team checked it's the same face as their profile photo. It doesn't check names, ID, or history.",
    pending: "Sent. Someone on our team will review it, usually within a day.",
    approved: "You're verified. The badge is on your profile.",
    needPhoto: "Add an approved profile photo first. We compare your video against it.",
    needPhotoCta: "Add a photo",
    explainer: {
      heading: "How it works",
      points: [
        "A short video, about 15 seconds: two quick actions and a 4-digit number read aloud.",
        "Only our review team watches it, to check it matches your profile photo.",
        "Stored privately and deleted 7 days after review.",
        "Best in good light, phone held at eye level. Works in the installed app too.",
      ],
      start: "Start camera",
    },
    holdCode: "Read aloud",
    ready: "Start recording",
    getReady: "Get ready",
    recording: "Recording",
    retake: "Retake",
    send: "Send for review",
    uploading: "Uploading…",
    uploadingPct: (p: number) => `Uploading… ${p}%`,
    sent: "Sent. We'll review it, usually within a day.",
    faceOk: "Face in frame",
    faceMissing: "Move your face into the frame",
    youllDo: "You'll be asked to",
    thenRead: "then read the number aloud.",
    actionPrompts: {
      turn_head_left: "Turn your head to the left",
      turn_head_right: "Turn your head to the right",
      look_up: "Look up",
      smile: "Smile",
      blink_twice: "Blink twice",
      show_fingers_2: "Hold up two fingers",
      show_fingers_3: "Hold up three fingers",
      show_fingers_5: "Hold up five fingers",
      touch_left_ear: "Touch your left ear",
      touch_right_ear: "Touch your right ear",
    } as Record<string, string>,
    readCodeNow: "Now read the number aloud",
    cameraBlocked: "Camera or microphone access is blocked. Allow it in your browser or phone settings, then try again.",
    cameraIosHint: "On iPhone: Settings → Safari (or the Tremigos app) → Camera & Microphone → Allow.",
    insecure: "The camera only works over a secure (https) connection.",
    noCamera: "We couldn't find a front camera on this device.",
    tooLarge: "That recording is too big. Try again and keep it short.",
    uploadFailed: "We couldn't upload that recording. Check your connection and try again.",
    fallbackNote: "Your browser can't record video here, so we'll take three photos at the prompts instead.",
    pendingStatus: "We've got your recording and will review it soon.",
    rejectedStatus: "Your last attempt didn't pass. You can record a new one.",
    verifyCta: "Get verified",
    tryAgain: "Try again",
    backToProfile: "Back to profile",
    rejectReasons: {
      face_not_clear: "We couldn't see your face clearly enough.",
      actions_not_performed: "The actions we asked for weren't done.",
      code_not_read: "The code on screen wasn't read out.",
      photo_mismatch: "This didn't look like the same person as your photo.",
      suspected_recording: "This looked pre-recorded, not live.",
      other: "Something wasn't right with this one.",
    } as Record<string, string>,
  },
} as const;
