/**
 * Every user-facing string lives here. Voice: warm, plain, a little playful,
 * never cute about safety. Sentence case. No exclamation marks in system copy.
 */
import { brand } from "@/lib/brand";

const N = brand.name;

export const copy = {
  productLine: "Plans need people. Find your crew.",

  nav: {
    feed: "Discover",
    myGigs: "My gigs",
    newGig: "Post a gig",
    me: "Profile",
    friends: "Friends",
    notifications: "Activity",
    admin: "Admin",
    signIn: "Sign in",
    getStarted: "Get started",
    signOut: "Sign out",
  },

  // ── Global disclaimers (shown in chat, lobby, invite page, footer) ────────
  disclaimers: {
    chat: "Keep it in the group. Don't share phone numbers, home addresses, or social handles in chat, and don't follow links to other sites — anything you take off Tremigos is at your own risk.",
    chatShort: "Don't share phone numbers or follow outside links — that's at your own risk.",
    phoneWarning: "Looks like you're sharing a phone number. We recommend keeping chat inside Tremigos — sharing contact details is at your own risk.",
    linkWarning: "Looks like you're sharing a link. People can't tell where links really go — sharing or opening them is at your own risk.",
    sendAnyway: "Send anyway",
    editMessage: "Edit message",
    receivedLink: "Outside link — open at your own risk",
    receivedPhone: "Contains contact details — be careful",
    meetPublic: "Meet in public, sort your own transport, and tell someone where you're going.",
    footer: `${N} connects people for group activities. We don't run, supervise or attend gigs. Meeting people you don't know carries risk — use your judgement, meet in public, and leave if anything feels off.`,
  },

  auth: {
    signInTitle: "Welcome back",
    signInSub: "Sign in to see what's on.",
    signUpTitle: "Create your account",
    signUpSub: "Takes a minute. You must be 18 or older.",
    name: "Your name",
    namePlaceholder: "First name is fine",
    username: "Username",
    usernamePlaceholder: "e.g. chanka",
    usernameHint: "3–20 characters: letters, numbers, underscores.",
    email: "Email",
    password: "Password",
    passwordHint: "At least 8 characters.",
    birthDate: "Date of birth",
    birthDateHint: "We show your age, never your birthday. Hosts can set an age range for their gigs.",
    gender: "Gender",
    genderHint: "Some gigs are women-only or men-only. This can't be changed later without contacting us.",
    genders: { woman: "Woman", man: "Man", nonbinary: "Non-binary" } as Record<string, string>,
    terms: "I'm 18 or older and I agree to the",
    termsLink: "Terms",
    and: "and",
    privacyLink: "Privacy Policy",
    signInCta: "Sign in",
    signUpCta: "Create account",
    working: "One sec…",
    toggleToSignUp: "New here? Create an account",
    toggleToSignIn: "Already have an account? Sign in",
    forgot: "Forgot password?",
    resetTitle: "Reset your password",
    resetSub: "We'll email you a link to set a new one.",
    resetCta: "Send reset link",
    resetSent: "If there's an account for that email, a reset link is on its way.",
    newPasswordTitle: "Choose a new password",
    newPasswordCta: "Save password",
    newPasswordDone: "Password updated.",
    backToSignIn: "Back to sign in",
    confirmEmail: "Almost there — we've sent you an email. Confirm your address, then sign in.",
    errors: {
      username_taken: "That username's taken. Try another.",
      username_format: "Usernames are 3–20 characters: letters, numbers, underscores.",
      bad_credentials: "That email or password isn't right.",
      email_in_use: "There's already an account with that email. Sign in instead.",
      email_not_confirmed: "Confirm your email first — check your inbox for the link.",
      weak_password: "Use at least 8 characters.",
      name_required: "Add your name.",
      email_invalid: "That email doesn't look right.",
      birth_required: "Add your date of birth.",
      underage: `You need to be 18 or older to use ${N}.`,
      gender_required: "Pick a gender.",
      terms_required: "You need to accept the Terms and Privacy Policy.",
      rate_limited: "Too many attempts. Wait a minute and try again.",
      generic: "That didn't work. Try again in a moment.",
    } as Record<string, string>,
  },

  onboarding: {
    title: "One more step",
    sub: "Hosts can open gigs to an age range or to women/men only, so we need these two things before you can join.",
    cta: "Continue",
  },

  feed: {
    title: "Discover",
    greeting: (name: string) => `Hey ${name}`,
    sub: "Gigs near you that are open to you.",
    all: "All",
    empty: "Nothing on yet. Someone has to go first — might as well be you.",
    emptyFiltered: "No gigs in this category right now. Post one and see who bites.",
    emptyCta: "Post a gig",
    fromFriends: "Hosted by your friends",
    audienceNote: "You only see gigs whose age range and audience include you.",
    seeGig: "View gig",
    spotsLeft: (n: number) => (n === 1 ? "1 spot left" : `${n} spots left`),
    full: "Full",
    locked: "Locked",
  },

  venue: {
    openInMaps: "Open in Google Maps",
    searchPlaceholder: "Search a café, court, park or venue",
    searchHint: "Public places only — home addresses aren't allowed.",
    searching: "Searching…",
    change: "Change venue",
    searchLabel: "Search venues",
  },

  slots: {
    needMore: (n: number) => (n === 1 ? "1 more to make it happen" : `${n} more to make it happen`),
    on: "It's on",
    hostTitle: "Host",
  },

  myGigs: {
    title: "My gigs",
    upcoming: "Upcoming",
    past: "Past",
    hosting: "Hosting",
    joined: "Joined",
    emptyUpcoming: "You're not in anything yet. Find a gig or post your own.",
    emptyPast: "Your finished gigs will show up here.",
    findGig: "Find a gig",
  },

  audience: {
    everyone: "Everyone",
    women: "Women only",
    men: "Men only",
    ages: (min: number, max: number) => (min === 18 && max === 99 ? "18+" : max === 99 ? `${min}+` : `${min}–${max}`),
  },

  guests: {
    badge: (n: number) => `Host +${n}`,
    feedNote: (n: number) => `The host is bringing ${n} ${n === 1 ? "friend" : "friends"} — join at your own risk.`,
    lobbyNote: (n: number) =>
      `The host is bringing ${n} ${n === 1 ? "person they know" : "people they know"}. They may already know each other, so the group dynamic might not be all strangers. Join at your own risk.`,
    ack: "I understand the host is bringing people they know, and I'm joining at my own risk.",
    reservedLeft: (n: number) => `${n} ${n === 1 ? "seat" : "seats"} held for the host's friends`,
  },

  gig: {
    confirmed: "It's on. Chat's open.",
    take: "Join this gig",
    joining: "Joining…",
    youreIn: "You're in",
    leave: "Leave gig",
    hostedBy: "Hosted by",
    mustAgree: "Tick the box to confirm you get what Tremigos is for.",
    needTime: "Pick a date and time first.",
    needVenue: "Pick a venue from the search.",
    perkTitle: "Perk for your crew",
    redeem: "Mark as redeemed",
    redeemed: "Redeemed",
    showCode: "Show this code at the venue",
    cancel: "Cancel gig",
    cancelConfirm: "Cancel this gig? Everyone in it will be told. Cancelling a gig that's already on counts against your reliability.",
    cancelDo: "Yes, cancel it",
    keep: "Keep it",
    cancelled: "This gig was cancelled.",
    status: {
      open: "Open",
      locked: "Locked in",
      completed: "Done",
      cancelled: "Cancelled",
      expired: "Expired",
    } as Record<string, string>,
  },

  newGig: {
    heading: "Post a gig",
    sub: "Pick the activity, set the time and place, and decide who it's for.",
    step1: "Activity",
    step2: "Details",
    step3: "Who's it for",
    step4: "Group size",
    pickActivity: "What are you up for?",
    title: "Give it a title",
    titlePlaceholder: "Friday night futsal, all levels",
    when: "Date & time",
    whenHint: "At least 3 hours from now. Joining closes 2 hours before it starts.",
    length: "Length",
    where: "Where",
    costNote: "Cost",
    optional: "optional",
    costPlaceholder: "Court fee ~LKR 1,000 each",
    notes: "Notes",
    notesPlaceholder: "Bring water. Beginners welcome.",
    audience: "Who can see and join",
    audienceHint: "People outside this won't see the gig at all.",
    ageRange: "Age range",
    ageRangeHint: "Your own age has to be inside the range.",
    gender: "Open to",
    howMany: "Total group size",
    howManyHint: "Including you. Minimum 3.",
    guests: "Bringing people you know?",
    guestsHint:
      "Hold seats for friends who are coming with you. Everyone will see that you're bringing people, and you'll get a link your friends can use to join the chat.",
    guestsNone: "Just me",
    openSpots: (n: number) => (n === 1 ? "1 spot open to the public" : `${n} spots open to the public`),
    submit: "Post the gig",
    submitting: "Posting…",
    minutes: "min",
  },

  invite: {
    title: "Invite your people",
    sub: "Share this link with the friends you're bringing. They'll need a Tremigos account, and they skip the age/audience filter because you're vouching for them.",
    copy: "Copy link",
    copied: "Copied",
    share: "Share",
    shareText: (title: string) => `Join me on Tremigos: ${title}`,
    release: "Release a held seat",
    releaseHint: "Not everyone coming? Give the seat back to the public.",
    landingTitle: (host: string) => `${host} invited you`,
    landingSub: "You've been invited to join this gig and its group chat.",
    joinCta: "Join with this invite",
    signInToJoin: "Sign up or sign in to join",
    notFound: "This invite link doesn't work any more. Ask the host for a new one.",
    alreadyIn: "You're already in this one.",
    friendsFeature: "Invite Tremigos friends",
    friendsHint: "A nudge only — it doesn't hold a seat for them.",
  },

  lobby: {
    whenWhere: "When & where",
    crew: "The crew",
    about: "About this gig",
    joinHint: "Spots are first-come. Join to see who else is in and unlock the group chat once it's on.",
    leaving: "Leaving?",
    somethingCameUp: "Something came up",
    didntFeelComfortable: "I didn't feel comfortable",
    leaveHint: "The second option never counts against you, at any time, and quietly flags it to our team.",
    neverMind: "Never mind",
    youAreHost: "You're hosting",
    invitedByHost: "Host's guest",
    you: "You",
    previewBlind: "Names and faces stay hidden until you join.",
    checkinTitle: "Who showed up?",
    checkinHint: "Tap everyone you actually met. It keeps reliability honest — and unlocks adding friends afterwards.",
    checkedIn: "Confirmed",
    confirm: "Confirm",
    notOpenToYou: "This gig isn't open to you.",
  },

  chat: {
    heading: "Group chat",
    lockedTitle: "Chat unlocks when the gig is on",
    beforeConfirm: (n: number) => (n <= 1 ? "One more person and this is on — chat opens then." : `${n} more people needed before chat opens.`),
    opens: "You're on. Sort out the details here.",
    readOnly: "This gig's finished. Chat is read-only and will be deleted after 30 days.",
    placeholder: "Message the crew",
    send: "Send",
    you: "You",
    someone: "Someone",
    system: {
      confirmed: "The gig is on — chat is open.",
      locked: "Crew's locked in. See you there.",
      left: "Someone left the gig.",
      removed: "The host removed someone from the gig.",
      vote_removed: "The crew voted someone out of the gig.",
      cancelled: "The host cancelled this gig.",
    } as Record<string, string>,
  },

  vote: {
    action: "Vote to remove",
    title: (name: string) => `Vote to remove ${name}?`,
    body: "Use this for bad behaviour in chat or at the gig — harassment, pushiness, spam, sharing others' details. Votes are anonymous to the crew. If a majority of the other members agree, they're removed and our team reviews it.",
    reason: "What happened?",
    reasonPlaceholder: "A few words about the behaviour",
    submit: "Cast my vote",
    retract: "Withdraw my vote",
    tally: (v: number, n: number) => `${v} of ${n} votes to remove`,
    youVoted: "You voted",
    removed: "They've been removed. Thanks for keeping the group safe.",
    recorded: "Vote recorded. Nothing happens unless enough of the crew agree.",
    retracted: "Vote withdrawn.",
    hostNote: "Hosts can't be voted out — if the host is the problem, leave and report them.",
  },

  verification: {
    title: "Verify you're you",
    meaning:
      "Verified means a real person recorded themselves live, and a person on our team checked it's the same face as their profile photo. It doesn't check names, ID, or history.",
    pending: "Sent. Someone on our team will review it — usually within a day.",
    approved: "You're verified. The badge is on your profile.",
    needPhoto: "Add an approved profile photo first — we compare your video against it.",
    needPhotoCta: "Add a photo",
    explainer: {
      heading: "How it works",
      points: [
        "A short video, about 15 seconds: two quick actions and a 4-digit number read aloud.",
        "Only our review team watches it, to check it matches your profile photo.",
        "Stored privately and deleted 7 days after review.",
        "Best in good light, phone held at eye level. Works in the installed app too.",
      ],
      start: "Start camera",
    },
    holdCode: "Read aloud",
    ready: "Start recording",
    getReady: "Get ready",
    recording: "Recording",
    retake: "Retake",
    send: "Send for review",
    uploading: "Uploading…",
    uploadingPct: (p: number) => `Uploading… ${p}%`,
    sent: "Sent. We'll review it — usually within a day.",
    faceOk: "Face in frame",
    faceMissing: "Move your face into the frame",
    youllDo: "You'll be asked to",
    thenRead: "then read the number aloud.",
    actionPrompts: {
      turn_head_left: "Turn your head to the left",
      turn_head_right: "Turn your head to the right",
      look_up: "Look up",
      smile: "Smile",
      blink_twice: "Blink twice",
      show_fingers_2: "Hold up two fingers",
      show_fingers_3: "Hold up three fingers",
      show_fingers_5: "Hold up five fingers",
      touch_left_ear: "Touch your left ear",
      touch_right_ear: "Touch your right ear",
    } as Record<string, string>,
    readCodeNow: "Now read the number aloud",
    cameraBlocked: "Camera or microphone access is blocked. Allow it in your browser or phone settings, then try again.",
    cameraIosHint: "On iPhone: Settings → Safari (or the Tremigos app) → Camera & Microphone → Allow.",
    insecure: "The camera only works over a secure (https) connection.",
    noCamera: "We couldn't find a front camera on this device.",
    tooLarge: "That recording is too big. Try again — keep it short.",
    uploadFailed: "We couldn't upload that recording. Check your connection and try again.",
    fallbackNote: "Your browser can't record video here, so we'll take three photos at the prompts instead.",
    pendingStatus: "We've got your recording and will review it soon.",
    rejectedStatus: "Your last attempt didn't pass. You can record a new one.",
    verifyCta: "Get verified",
    tryAgain: "Try again",
    backToProfile: "Back to profile",
    rejectReasons: {
      face_not_clear: "We couldn't see your face clearly enough.",
      actions_not_performed: "The actions we asked for weren't done.",
      code_not_read: "The code on screen wasn't read out.",
      photo_mismatch: "This didn't look like the same person as your photo.",
      suspected_recording: "This looked pre-recorded, not live.",
      other: "Something wasn't right with this one.",
    } as Record<string, string>,
  },

  photo: {
    title: "Profile photo",
    hint: "A clear photo of your face, just you. It's checked by our team before anyone sees it, and only people in your gigs see it.",
    choose: "Upload a photo",
    change: "Change photo",
    checking: "Checking for a face…",
    uploading: "Uploading…",
    noFace: "We couldn't find a face in that photo. Use a clear, well-lit photo of just you.",
    manyFaces: "We found more than one face. Use a photo of just you.",
    pending: "Under review — it'll appear once approved.",
    approved: "Approved",
    rejected: "Your last photo wasn't approved",
    rejectReasons: {
      no_face: "We couldn't see a face.",
      not_you: "It didn't look like a real photo of you.",
      group_photo: "More than one person was in it.",
      inappropriate: "It broke our photo rules.",
      low_quality: "It was too blurry or dark.",
    } as Record<string, string>,
    tooBig: "That image is too large. Try a different one.",
    badType: "Use a JPG, PNG or WebP image.",
  },

  profile: {
    edit: "Edit profile",
    save: "Save changes",
    saved: "Saved",
    bio: "About you",
    bioPlaceholder: "What are you into? What are you looking for?",
    age: (n: number) => `${n}`,
    hostedCount: "Hosted",
    joinedCount: "Joined",
    reliability: "Reliability",
    notVerified: "Not verified",
    settings: "Account",
    installApp: "Install the app",
    deleteAccount: "Delete account",
    deleteConfirm: "This permanently deletes your account, profile, photos and gig history. Reports and moderation records are kept without your name. This can't be undone.",
    deleteType: "Type DELETE to confirm",
    deleteDo: "Delete my account",
    lockedField: "Contact us to change this.",
  },

  friends: {
    title: "Friends",
    requestSent: "Sent. If they add you back, you'll see the gigs they host.",
    requestReceived: (name: string, activity: string, date: string) =>
      `${name} wants to add you after ${activity} on ${date}.`,
    listEmpty: "No friends yet. Go to a gig, have a good time, add people afterwards.",
    yourFriends: "Your friends",
    incoming: "Wants to add you",
    outgoing: "Requests you sent",
    outgoingHint: "Waiting to hear back. You'll know if they add you — and only then.",
    add: "Add friend",
    added: "Request sent",
    accept: "Add back",
    unfriend: "Remove",
    invite: "Invite",
    inviteSent: "Invited",
    summaryTitle: "You did this together",
    summaryHint: "Had a good time with someone? Add them. You can only add people you actually met.",
    whyNoDms: {
      heading: "Why no private messages?",
      body: "Every conversation here happens with at least three people in it, on purpose. Private threads are how a friends app quietly turns into a dating app — and how people end up in one-on-one chats they didn't sign up for.",
      body2: "Adding a friend means their gigs show up for you and you can nudge them into yours. Want to talk? Post a plan.",
    },
  },

  notifications: {
    title: "Activity",
    empty: "Nothing yet. Updates about your gigs will show up here.",
    markRead: "Mark all read",
    kinds: {
      gig_confirmed: "Your gig is on — the group chat is open.",
      gig_locked: "Your gig is locked in. Check the details.",
      gig_cancelled: "A gig you were in was cancelled.",
      removed: "You were removed from a gig by the host.",
      removed_by_vote: "The crew voted to remove you from a gig. Our team will review it.",
      verification_approved: "You're verified.",
      verification_rejected: "Your verification didn't pass. You can try again.",
      photo_approved: "Your profile photo was approved.",
      photo_rejected: "Your profile photo wasn't approved. Try another one.",
      friend_request: "Someone you met wants to add you as a friend.",
      friend_accepted: "Your friend request was accepted.",
      friend_invite: "A friend invited you to their gig.",
      moderation_action: "There's an update about your account. Check your email.",
      admin_priority_report: "Priority report waiting for review.",
    } as Record<string, string>,
  },

  trust: {
    report: {
      title: "Report",
      intro: "Goes to our team only — never shown to the person or the rest of the crew.",
      category: "What happened?",
      details: "Tell us a bit more",
      detailsPlaceholder: "What happened, and when.",
      submit: "Send report",
      sent: "Thanks. Someone on our team will look into it.",
      categories: {
        harassment: "Harassment or bullying",
        sexual_advance: "Unwanted romantic or sexual advance",
        pressured_private_meeting: "Pushed to meet one-on-one",
        sharing_contact: "Pushed to share contact details",
        venue_changed_to_private: "Tried to move it somewhere private",
        no_show: "Didn't show up",
        impersonation: "Not who their photo says",
        underage: "Seems under 18",
        spam_or_promo: "Selling, spam or scam links",
        threat_or_violence: "Threat or violence",
        other: "Something else",
      } as Record<string, string>,
    },
    block: {
      action: "Block",
      confirmTitle: "Block this person?",
      confirmBody: "You won't see each other's gigs again and can't end up in the same gig. They won't be told.",
      confirm: "Block",
      done: "Blocked.",
    },
    remove: {
      action: "Remove (host)",
      title: "Remove from your gig",
      intro: "Removals are logged and reviewed. Use this for a real problem, not because you'd prefer someone else.",
      category: "Why?",
      reasonPlaceholder: "Add a short reason — at least ten characters.",
      submit: "Remove",
      categories: {
        abusive_in_chat: "Abusive in chat",
        pushing_for_one_on_one: "Pushing to meet one-on-one",
        sharing_contact: "Pushing for contact details",
        misrepresented_themselves: "Not who they said they were",
        safety_concern: "Safety concern",
        other: "Something else",
      } as Record<string, string>,
    },
    cancel: "Cancel",
    close: "Close",
  },

  errors: {
    gig_full: "That gig just filled up. There are others on.",
    gig_locked: "Joining closed 2 hours before the start.",
    gig_not_open: "This gig isn't taking people right now.",
    gig_not_found: "That gig's gone.",
    gig_not_active: "This gig has finished.",
    already_in_crew: "You're already in this one.",
    removed_from_gig: "You can't rejoin a gig you were removed from.",
    not_eligible: "This gig is set for a different age range or audience.",
    account_restricted: "You can't join gigs right now. Check your email for details.",
    not_authenticated: "Sign in first.",
    profile_incomplete: "Add your date of birth and gender first.",
    profile_missing: "Your profile isn't set up yet. Reload and try again.",
    capacity_too_low: "A gig needs at least three people.",
    capacity_too_high: "Keep it to 16 people or fewer.",
    too_many_guests: "Leave at least one spot open for the public.",
    bad_age_range: "Check the age range.",
    host_outside_age_range: "Your own age needs to be inside the age range.",
    host_gender_mismatch: "You can only host a women-only or men-only gig if you're in that group.",
    too_many_open_gigs: "You've got 5 upcoming gigs already. Let some happen first.",
    starts_too_soon: "Give people time to see it — start at least 3 hours from now.",
    starts_too_far: "Keep it within the next 60 days.",
    posting_restricted: "You can't host gigs right now. Check your email.",
    reason_too_short: "Add a bit more detail.",
    already_removed_from_gig: "You've already removed someone from this gig.",
    removal_limit_reached: "You've hit the removal limit for this month. Email us if there's a real problem.",
    cannot_report_self: "You can't report yourself.",
    too_many_reports: "You've sent a lot of reports today. Email us if it's urgent.",
    details_required: "Add a short description.",
    chat_not_open: "Voting opens once the gig is on.",
    cannot_vote_self: "You can't vote on yourself.",
    cannot_kick_host: "Hosts can't be voted out — leave and report them instead.",
    not_enough_voters: "There need to be at least two other people in the gig to vote. Leave and report instead.",
    target_not_in_crew: "They're not in this gig any more.",
    not_in_crew: "You're not in this gig.",
    invite_not_found: "This invite link doesn't work any more.",
    nothing_reserved: "There are no held seats left.",
    checkin_closed: "Check-in is open from 30 minutes before the start.",
    residential: "That looks like a home address. Gigs must be at a public place — a café, court, park or venue.",
    no_shared_attendance: "You can only add people you've actually been to a gig with.",
    recently_asked: "You've already asked. Give it some time.",
    too_many_pending: "You've got a lot of requests out. Wait for some answers first.",
    not_available: "That didn't work. Try again later.",
    verification_cooldown: "Your last attempt didn't pass, so there's a short wait before trying again.",
    verification_rate_limited: "You've had a few goes today. Try again tomorrow.",
    challenge_expired: "That took too long and the code expired. Let's start again.",
    already_submitted: "This one's already in for review.",
    already_verified: "You're already verified.",
    bad_media_path: "Something went wrong saving that recording. Try again.",
    request_not_found: "That session expired. Start again.",
    underage: "You need to be 18 or older.",
    already_redeemed: "Already redeemed.",
    not_host: "Only the host can do that.",
    generic: "That didn't work. Try again in a moment.",
  } as Record<string, string>,

  safetyReminder:
    "Meet at the venue. Sort your own transport. Tell someone where you're going. If it feels off, leave — you'll never be penalised for it.",

  platonicClause: {
    heading: "Not a dating app. On purpose.",
    body: "Every gig needs three people minimum, because three people isn't a date. Nobody hand-picks who joins — spots go first-come. And there are no private messages: every conversation happens in the group.",
    checkbox:
      "I get it — this is for doing things with people, not dating. Groups of three or more, public places, no hitting on the crew.",
  },

  install: {
    title: "Install Tremigos",
    body: "Add it to your home screen for the full-screen app — faster, works with your camera for verification, and opens straight to your gigs.",
    cta: "Install app",
    later: "Not now",
    iosTitle: "Install on iPhone",
    iosSteps: ["Tap the Share button in Safari", "Scroll and tap “Add to Home Screen”", "Tap “Add”"],
    iosSafariOnly: "On iPhone, open this page in Safari to install.",
    installed: "You're using the app.",
  },

  spot: {
    title: "Tremigos crew perk",
    intro: "A Tremigos crew here? Enter their gig code to log the visit.",
    codeLabel: "Gig code",
    submit: "Log the visit",
    done: "Logged. Thanks — that helps us show we're sending you people.",
    errors: {
      venue_not_found: "We couldn't find this venue.",
      gig_not_found: "No crew found for that code here. Check it and try again.",
      already_redeemed: "This one's already been logged.",
      generic: "That didn't work. Try again.",
    } as Record<string, string>,
  },

  notFound: {
    title: "Nothing here",
    body: "That page doesn't exist, or it isn't open to you.",
    feed: "Back to Discover",
    home: "Or the home page",
  },

  offline: "You're offline. Some things won't load until you're back online.",

  landing: {
    eyebrow: "Now in Colombo",
    heroTitle: "Plans need people.",
    heroAccent: "Find your crew.",
    heroSub:
      "Short a few players for futsal? Want company for a hike, a quiz night or coffee? Post it, people nearby claim the spots, and you meet up — in groups of three or more, always somewhere public.",
    ctaPrimary: "Get started — it's free",
    ctaSecondary: "How it works",
    howTitle: "How it works",
    howItWorks: [
      { title: "Post a plan", body: "Pick the activity, time and a public spot. Choose who it's for — an age range, women-only, men-only, or everyone." },
      { title: "Spots fill up", body: "People nearby claim the open spots, first-come. Bringing friends? Hold seats for them and share an invite link." },
      { title: "Meet your crew", body: "Once enough people are in, it's on. Faces reveal, the group chat opens, and you sort out the rest." },
    ],
    featuresTitle: "Built for meeting people safely",
    features: [
      { title: "Groups only", body: "Three-person minimum and no private DMs. It's for crews, not dates." },
      { title: "Real faces", body: "Profile photos are reviewed by our team, and optional live video verification puts a badge on real people." },
      { title: "Your audience", body: "Hosts set the age range and audience. Gigs outside yours never show up." },
      { title: "Crew has a say", body: "If someone's out of line, the group can vote them out — and our team follows up." },
      { title: "Bring your friends", body: "Hold seats for people you know and share a private invite link to the group chat." },
      { title: "Install it", body: "Add Tremigos to your home screen and it runs like a native app." },
    ],
    activitiesTitle: "Whatever you're into",
    safetyTitle: "Safety, without the theatre",
    safetyBody:
      "We verify faces, not backgrounds — and we say so. Meet in public, keep chat on Tremigos, and leave whenever you want. The “I didn't feel comfortable” exit never counts against you.",
    safetyCta: "Read our safety approach",
    finalTitle: "Your next plan is three people away.",
    finalSub: "Free to join. 18+. Colombo first, the rest of Sri Lanka soon.",
  },

  about: {
    title: `About ${N}`,
    body: [
      `${N} is for doing things with people. Post a plan — futsal, a film, board games, a hike, coffee — and others claim the open spots. Three minimum. You meet in real life.`,
      "The activity comes first, not friendship in the abstract. You want to play on Saturday and you need a few more people. Friendship is the side effect.",
      "It's deliberately not a dating app, and it's built that way: groups of three or more, no hand-picking who joins, and no private messages.",
    ],
  },

  safety: {
    title: "Safety, honestly",
    intro: "Here's exactly what we do and don't do. A safety page that oversells is worse than none.",
    weCheckTitle: "What we check",
    weCheck: [
      "Profile photos are reviewed by a person before anyone sees them.",
      "Optional live video verification: a real person, matching their photo.",
      "Every gig is three or more people, at a public place.",
      "Reports are read by a person, and crew votes are reviewed.",
    ],
    weDontTitle: "What we don't do",
    weDont: [
      "Background or criminal checks.",
      "ID or NIC verification.",
      "Guarantee how anyone will behave.",
    ],
    tipsTitle: "When you meet",
    meetingTips: [
      "Meet at the venue and sort your own transport.",
      "Tell someone where you're going and who with.",
      "Keep chat on Tremigos — don't hand out your number or follow outside links.",
      "If a host is bringing friends, the group may know each other. Factor that in.",
      "If it feels off, leave. Use “I didn't feel comfortable” — it never counts against you.",
    ],
    rulesTitle: "Community rules",
    rules: [
      "18+ only. No exceptions.",
      "Show up, or leave the gig early so someone else can take the spot.",
      "Groups of three or more, in public. Don't push anyone toward one-on-one.",
      "Don't hit on the crew. That's not what this is.",
      "Your photo has to be you.",
      "No selling, recruiting, or spam links.",
      "No pressuring anyone for phone numbers or socials.",
    ],
    emergency: "In an emergency in Sri Lanka call 119 (Police) or 1990 (Suwa Seriya ambulance).",
  },
} as const;

/** Map a thrown Postgres exception message to friendly copy. */
export function errorCopy(code: string | undefined | null): string {
  if (!code) return copy.errors.generic;
  return copy.errors[code] ?? copy.errors.generic;
}
